import { getCloudinaryUrl } from "../lib/cloudinary";

export const CARDAPIO_OFICIAL_URL =
  "https://drive.google.com/drive/u/0/folders/1rDie7Qz6-Cl34sLO0ReUTStuOnR6a_Db";

export const DELIVERY_URL = "https://linktr.ee/mandacafe.foradacasinha";

export const cardapioImagens = [
  {
    id: 1,
    title: "Linguine à Bolonhesa",
    publicId: "pratoc1_maosov",
    url: getCloudinaryUrl("pratoc1_maosov", 900),
    fullUrl: getCloudinaryUrl("pratoc1_maosov", 1600),
    width: 4,
    height: 5,
    alt: "Linguine à Bolonhesa",
  },
  {
    id: 2,
    title: "Linguine Três Queijos com Filé Mignon",
    publicId: "pratoc2_ocecz8",
    url: getCloudinaryUrl("pratoc2_ocecz8", 900),
    fullUrl: getCloudinaryUrl("pratoc2_ocecz8", 1600),
    width: 4,
    height: 5,
    alt: "Linguine Três Queijos com Filé Mignon",
  },
  {
    id: 3,
    title: "Linguine ao Sugo com Filé Mignon",
    publicId: "pratoc3_dkucws",
    url: getCloudinaryUrl("pratoc3_dkucws", 900),
    fullUrl: getCloudinaryUrl("pratoc3_dkucws", 1600),
    width: 4,
    height: 5,
    alt: "Linguine ao Sugo com Filé Mignon",
  },
  {
    id: 4,
    title: "Raviolloni",
    publicId: "pratoc4_fcknpn",
    url: getCloudinaryUrl("pratoc4_fcknpn", 900),
    fullUrl: getCloudinaryUrl("pratoc4_fcknpn", 1600),
    width: 4,
    height: 5,
    alt: "Raviolloni",
  },
  {
    id: 5,
    title: "Salada de Grãos",
    publicId: "pratoc5_zr0aer",
    url: getCloudinaryUrl("pratoc5_zr0aer", 900),
    fullUrl: getCloudinaryUrl("pratoc5_zr0aer", 1600),
    width: 4,
    height: 5,
    alt: "Salada de Grãos",
  },
  {
    id: 6,
    title: "Salada Manda",
    publicId: "pratoc6_mervk1",
    url: getCloudinaryUrl("pratoc6_mervk1", 900),
    fullUrl: getCloudinaryUrl("pratoc6_mervk1", 1600),
    width: 4,
    height: 5,
    alt: "Salada Manda",
  },
  {
    id: 7,
    title: "Filé de Frango Grelhado",
    publicId: "pratoc7_u4w7jg",
    url: getCloudinaryUrl("pratoc7_u4w7jg", 900),
    fullUrl: getCloudinaryUrl("pratoc7_u4w7jg", 1600),
    width: 4,
    height: 5,
    alt: "Filé de Frango Grelhado",
  },
  {
    id: 8,
    title: "Saint Peter Empanado",
    publicId: "pratoc8_f58frg",
    url: getCloudinaryUrl("pratoc8_f58frg", 900),
    fullUrl: getCloudinaryUrl("pratoc8_f58frg", 1600),
    width: 4,
    height: 5,
    alt: "Saint Peter Empanado",
  },
  {
    id: 9,
    title: "Kibe de Carne",
    publicId: "pratoc9_o2wgyu",
    url: getCloudinaryUrl("pratoc9_o2wgyu", 900),
    fullUrl: getCloudinaryUrl("pratoc9_o2wgyu", 1600),
    width: 4,
    height: 5,
    alt: "Kibe de Carne",
  },
  {
    id: 10,
    title: "Kibe de Abóbora",
    publicId: "pratoc10_ww7lzd",
    url: getCloudinaryUrl("pratoc10_ww7lzd", 900),
    fullUrl: getCloudinaryUrl("pratoc10_ww7lzd", 1600),
    width: 4,
    height: 5,
    alt: "Kibe de Abóbora",
  },
  {
    id: 11,
    title: "Omelete com Salada",
    publicId: "pratoc11_fnztrk",
    url: getCloudinaryUrl("pratoc11_fnztrk", 900),
    fullUrl: getCloudinaryUrl("pratoc11_fnztrk", 1600),
    width: 4,
    height: 5,
    alt: "Omelete com Salada",
  },
  {
    id: 12,
    title: "Strogonoff de Mignon",
    publicId: "pratoc12_scrrhi",
    url: getCloudinaryUrl("pratoc12_scrrhi", 900),
    fullUrl: getCloudinaryUrl("pratoc12_scrrhi", 1600),
    width: 4,
    height: 5,
    alt: "Strogonoff de Mignon",
  },
  {
    id: 13,
    title: "Strogonoff de Frango",
    publicId: "pratoc13_gbmsxj",
    url: getCloudinaryUrl("pratoc13_gbmsxj", 900),
    fullUrl: getCloudinaryUrl("pratoc13_gbmsxj", 1600),
    width: 4,
    height: 5,
    alt: "Strogonoff de Frango",
  },
  {
    id: 14,
    title: "Strogonoff de Cogumelos",
    publicId: "pratoc14_h8ngoq",
    url: getCloudinaryUrl("pratoc14_h8ngoq", 900),
    fullUrl: getCloudinaryUrl("pratoc14_h8ngoq", 1600),
    width: 4,
    height: 5,
    alt: "Strogonoff de Cogumelos",
  },
  {
    id: 15,
    title: "Americano",
    publicId: "pratoc15_vfwd0u",
    url: getCloudinaryUrl("pratoc15_vfwd0u", 900),
    fullUrl: getCloudinaryUrl("pratoc15_vfwd0u", 1600),
    width: 4,
    height: 5,
    alt: "Americano",
  },
  {
    id: 16,
    title: "Ciabata Caprese",
    publicId: "pratoc16_qcsth9",
    url: getCloudinaryUrl("pratoc16_qcsth9", 900),
    fullUrl: getCloudinaryUrl("pratoc16_qcsth9", 1600),
    width: 4,
    height: 5,
    alt: "Ciabata Caprese",
  },
  {
    id: 17,
    title: "Brigadeiro",
    publicId: "pratoc17_geydjs",
    url: getCloudinaryUrl("pratoc17_geydjs", 900),
    fullUrl: getCloudinaryUrl("pratoc17_geydjs", 1600),
    width: 4,
    height: 5,
    alt: "Brigadeiro",
  },
  {
    id: 18,
    title: "Torta de Maracujá",
    publicId: "pratoc18_hp64xv",
    url: getCloudinaryUrl("pratoc18_hp64xv", 900),
    fullUrl: getCloudinaryUrl("pratoc18_hp64xv", 1600),
    width: 4,
    height: 5,
    alt: "Torta de Maracujá",
  },
  {
    id: 19,
    title: "Torta de Limão",
    publicId: "pratoc19_ma4t7j",
    url: getCloudinaryUrl("pratoc19_ma4t7j", 900),
    fullUrl: getCloudinaryUrl("pratoc19_ma4t7j", 1600),
    width: 4,
    height: 5,
    alt: "Torta de Limão",
  },
  {
    id: 20,
    title: "Banoffee",
    publicId: "pratoc20_xv3fba",
    url: getCloudinaryUrl("pratoc20_xv3fba", 900),
    fullUrl: getCloudinaryUrl("pratoc20_xv3fba", 1600),
    width: 4,
    height: 5,
    alt: "Banoffee",
  },
];
