import { getCloudinaryUrl } from "../lib/cloudinary";

export const galleryCategories = [
  { id: "all", label: "Todos" },
  { id: "manda-festas", label: "Manda Festas" },
  { id: "casa-manda", label: "A Casa Manda" },
  { id: "manda-natureza", label: "Manda Natureza" },
  { id: "manda-pet", label: "Manda Pet" },
  { id: "dia-a-dia", label: "Dia a Dia do Manda" },
  { id: "memorias-manda", label: "Memórias do Manda" },
];

export const galleryImages = [
  {
    id: 1,
    url: getCloudinaryUrl("festa1_mterte"),
    fullUrl: getCloudinaryUrl("festa1_mterte", 1600),
    alt: "Manda Festas",
    category: "manda-festas",
  },
  {
    id: 2,
    url: getCloudinaryUrl("casa1_ztn2sa"),
    fullUrl: getCloudinaryUrl("casa1_ztn2sa", 1600),
    alt: "A Casa Manda",
    category: "casa-manda",
  },
  {
    id: 3,
    url: getCloudinaryUrl("flor1_jnk1aa"),
    fullUrl: getCloudinaryUrl("flor1_jnk1aa", 1600),
    alt: "Manda Natureza",
    category: "manda-natureza",
  },
  {
    id: 4,
    url: getCloudinaryUrl("pet1_jybmt2"),
    fullUrl: getCloudinaryUrl("pet1_jybmt2", 1600),
    alt: "Manda Pet",
    category: "manda-pet",
  },
  {
    id: 5,
    url: getCloudinaryUrl("dia1_dowkrc"),
    fullUrl: getCloudinaryUrl("dia1_dowkrc", 1600),
    alt: "Dia a Dia do Manda",
    category: "dia-a-dia",
  },
  {
    id: 6,
    url: getCloudinaryUrl("memorias1_hnbe3d"),
    fullUrl: getCloudinaryUrl("memorias1_hnbe3d", 1600),
    alt: "Memórias do Manda",
    category: "memorias-manda",
  },
  {
    id: 7,
    url: getCloudinaryUrl("festa2_kijkkj"),
    fullUrl: getCloudinaryUrl("festa2_kijkkj", 1600),
    alt: "Manda Festas",
    category: "manda-festas",
  },
  {
    id: 8,
    url: getCloudinaryUrl("flor2_jg5btd"),
    fullUrl: getCloudinaryUrl("flor2_jg5btd", 1600),
    alt: "Manda Natureza",
    category: "manda-natureza",
  },
  {
    id: 9,
    url: getCloudinaryUrl("casa7_tl7rwy"),
    fullUrl: getCloudinaryUrl("casa7_tl7rwy", 1600),
    alt: "A Casa Manda",
    category: "casa-manda",
  },
  {
    id: 10,
    url: getCloudinaryUrl("pet2_ynychp"),
    fullUrl: getCloudinaryUrl("pet2_ynychp", 1600),
    alt: "Manda Pet",
    category: "manda-pet",
  },
  {
    id: 11,
    url: getCloudinaryUrl("festa3_eqzjpi"),
    fullUrl: getCloudinaryUrl("festa3_eqzjpi", 1600),
    alt: "Manda Festas",
    category: "manda-festas",
  },
  {
    id: 12,
    url: getCloudinaryUrl("dia2_k2v8zy"),
    fullUrl: getCloudinaryUrl("dia2_k2v8zy", 1600),
    alt: "Dia a Dia do Manda",
    category: "dia-a-dia",
  },
  {
    id: 13,
    url: getCloudinaryUrl("memorias2_p06uta"),
    fullUrl: getCloudinaryUrl("memorias2_p06uta", 1600),
    alt: "Memórias do Manda",
    category: "memorias-manda",
  },
  {
    id: 14,
    url: getCloudinaryUrl("flor3_tvmmvj"),
    fullUrl: getCloudinaryUrl("flor3_tvmmvj", 1600),
    alt: "Manda Natureza",
    category: "manda-natureza",
  },
  {
    id: 15,
    url: getCloudinaryUrl("festa4_lzd0x0"),
    fullUrl: getCloudinaryUrl("festa4_lzd0x0", 1600),
    alt: "Manda Festas",
    category: "manda-festas",
  },
  {
    id: 16,
    url: getCloudinaryUrl("casa3_puwsol"),
    fullUrl: getCloudinaryUrl("casa3_puwsol", 1600),
    alt: "A Casa Manda",
    category: "casa-manda",
  },
  {
    id: 17,
    url: getCloudinaryUrl("pet3_x791ty"),
    fullUrl: getCloudinaryUrl("pet3_x791ty", 1600),
    alt: "Manda Pet",
    category: "manda-pet",
  },
  {
    id: 18,
    url: getCloudinaryUrl("dia3_vnkjuc"),
    fullUrl: getCloudinaryUrl("dia3_vnkjuc", 1600),
    alt: "Dia a Dia do Manda",
    category: "dia-a-dia",
  },
  {
    id: 19,
    url: getCloudinaryUrl("festa5_z1zpnc"),
    fullUrl: getCloudinaryUrl("festa5_z1zpnc", 1600),
    alt: "Manda Festas",
    category: "manda-festas",
  },
  {
    id: 20,
    url: getCloudinaryUrl("memorias3_huyllb"),
    fullUrl: getCloudinaryUrl("memorias3_huyllb", 1600),
    alt: "Memórias do Manda",
    category: "memorias-manda",
  },
  {
    id: 21,
    url: getCloudinaryUrl("flor4_npvwnq"),
    fullUrl: getCloudinaryUrl("flor4_npvwnq", 1600),
    alt: "Manda Natureza",
    category: "manda-natureza",
  },
  {
    id: 22,
    url: getCloudinaryUrl("casa4_egh4wc"),
    fullUrl: getCloudinaryUrl("casa4_egh4wc", 1600),
    alt: "A Casa Manda",
    category: "casa-manda",
  },
  {
    id: 23,
    url: getCloudinaryUrl("festa6_jabqgi"),
    fullUrl: getCloudinaryUrl("festa6_jabqgi", 1600),
    alt: "Manda Festas",
    category: "manda-festas",
  },
  {
    id: 24,
    url: getCloudinaryUrl("pet4_au0809"),
    fullUrl: getCloudinaryUrl("pet4_au0809", 1600),
    alt: "Manda Pet",
    category: "manda-pet",
  },
  {
    id: 25,
    url: getCloudinaryUrl("dia4_faegbm"),
    fullUrl: getCloudinaryUrl("dia4_faegbm", 1600),
    alt: "Dia a Dia do Manda",
    category: "dia-a-dia",
  },
  {
    id: 26,
    url: getCloudinaryUrl("memorias4_knrm47"),
    fullUrl: getCloudinaryUrl("memorias4_knrm47", 1600),
    alt: "Memórias do Manda",
    category: "memorias-manda",
  },
  {
    id: 27,
    url: getCloudinaryUrl("festa7_n1snd9"),
    fullUrl: getCloudinaryUrl("festa7_n1snd9", 1600),
    alt: "Manda Festas",
    category: "manda-festas",
  },
  {
    id: 28,
    url: getCloudinaryUrl("flor5_if2omh"),
    fullUrl: getCloudinaryUrl("flor5_if2omh", 1600),
    alt: "Manda Natureza",
    category: "manda-natureza",
  },
  {
    id: 29,
    url: getCloudinaryUrl("casa5_vrkj96"),
    fullUrl: getCloudinaryUrl("casa5_vrkj96", 1600),
    alt: "A Casa Manda",
    category: "casa-manda",
  },
  {
    id: 30,
    url: getCloudinaryUrl("pet5_ak4rbc"),
    fullUrl: getCloudinaryUrl("pet5_ak4rbc", 1600),
    alt: "Manda Pet",
    category: "manda-pet",
  },
  {
    id: 31,
    url: getCloudinaryUrl("festa8_dc3lzc"),
    fullUrl: getCloudinaryUrl("festa8_dc3lzc", 1600),
    alt: "Manda Festas",
    category: "manda-festas",
  },
  {
    id: 32,
    url: getCloudinaryUrl("dia5_zoks1m"),
    fullUrl: getCloudinaryUrl("dia5_zoks1m", 1600),
    alt: "Dia a Dia do Manda",
    category: "dia-a-dia",
  },
  {
    id: 33,
    url: getCloudinaryUrl("memorias5_tdexra"),
    fullUrl: getCloudinaryUrl("memorias5_tdexra", 1600),
    alt: "Memórias do Manda",
    category: "memorias-manda",
  },
  {
    id: 34,
    url: getCloudinaryUrl("flor6_bbklkq"),
    fullUrl: getCloudinaryUrl("flor6_bbklkq", 1600),
    alt: "Manda Natureza",
    category: "manda-natureza",
  },
  {
    id: 35,
    url: getCloudinaryUrl("festa9_iiviq3"),
    fullUrl: getCloudinaryUrl("festa9_iiviq3", 1600),
    alt: "Manda Festas",
    category: "manda-festas",
  },
  {
    id: 36,
    url: getCloudinaryUrl("casa6_ujg2yd"),
    fullUrl: getCloudinaryUrl("casa6_ujg2yd", 1600),
    alt: "A Casa Manda",
    category: "casa-manda",
  },
  {
    id: 37,
    url: getCloudinaryUrl("pet6_rxmtor"),
    fullUrl: getCloudinaryUrl("pet6_rxmtor", 1600),
    alt: "Manda Pet",
    category: "manda-pet",
  },
  {
    id: 38,
    url: getCloudinaryUrl("dia6_h9fwmw"),
    fullUrl: getCloudinaryUrl("dia6_h9fwmw", 1600),
    alt: "Dia a Dia do Manda",
    category: "dia-a-dia",
  },
  {
    id: 39,
    url: getCloudinaryUrl("festa10_k2ftdh"),
    fullUrl: getCloudinaryUrl("festa10_k2ftdh", 1600),
    alt: "Manda Festas",
    category: "manda-festas",
  },
  {
    id: 40,
    url: getCloudinaryUrl("memorias6_vbrvfi"),
    fullUrl: getCloudinaryUrl("memorias6_vbrvfi", 1600),
    alt: "Memórias do Manda",
    category: "memorias-manda",
  },
  {
    id: 41,
    url: getCloudinaryUrl("flor7_zdmkxf"),
    fullUrl: getCloudinaryUrl("flor7_zdmkxf", 1600),
    alt: "Manda Natureza",
    category: "manda-natureza",
  },
  {
    id: 42,
    url: getCloudinaryUrl("casa2_ayrhjo"),
    fullUrl: getCloudinaryUrl("casa2_ayrhjo", 1600),
    alt: "A Casa Manda",
    category: "casa-manda",
  },
  {
    id: 43,
    url: getCloudinaryUrl("pet7_kkfzli"),
    fullUrl: getCloudinaryUrl("pet7_kkfzli", 1600),
    alt: "Manda Pet",
    category: "manda-pet",
  },
  {
    id: 44,
    url: getCloudinaryUrl("dia7_nu6iap"),
    fullUrl: getCloudinaryUrl("dia7_nu6iap", 1600),
    alt: "Dia a Dia do Manda",
    category: "dia-a-dia",
  },
  {
    id: 45,
    url: getCloudinaryUrl("festa11_nhqhxp"),
    fullUrl: getCloudinaryUrl("festa11_nhqhxp", 1600),
    alt: "Manda Festas",
    category: "manda-festas",
  },
  {
    id: 46,
    url: getCloudinaryUrl("memorias7_pdzywh"),
    fullUrl: getCloudinaryUrl("memorias7_pdzywh", 1600),
    alt: "Memórias do Manda",
    category: "memorias-manda",
  },
  {
    id: 47,
    url: getCloudinaryUrl("festa12_o76m62"),
    fullUrl: getCloudinaryUrl("festa12_o76m62", 1600),
    alt: "Manda Festas",
    category: "manda-festas",
  },
  {
    id: 48,
    url: getCloudinaryUrl("pet8_wibebf"),
    fullUrl: getCloudinaryUrl("pet8_wibebf", 1600),
    alt: "Manda Pet",
    category: "manda-pet",
  },
  {
    id: 49,
    url: getCloudinaryUrl("casa8_lajygh"),
    fullUrl: getCloudinaryUrl("casa8_lajygh", 1600),
    alt: "A Casa Manda",
    category: "casa-manda",
  },
  {
    id: 50,
    url: getCloudinaryUrl("dia8_mtpgh6"),
    fullUrl: getCloudinaryUrl("dia8_mtpgh6", 1600),
    alt: "Dia a Dia do Manda",
    category: "dia-a-dia",
  },
  {
    id: 51,
    url: getCloudinaryUrl("memorias8_zbcden"),
    fullUrl: getCloudinaryUrl("memorias8_zbcden", 1600),
    alt: "Memórias do Manda",
    category: "memorias-manda",
  },
  {
    id: 52,
    url: getCloudinaryUrl("flor8_rwmysn"),
    fullUrl: getCloudinaryUrl("flor8_rwmysn", 1600),
    alt: "Manda Natureza",
    category: "manda-natureza",
  },
];
