// src/data/menuItems.js
export const MENU_ITEMS = [
  {
    id: 1,
    name: "Salada Manda",
    desc: "Frango grelhado com mix de folhas...",
    price: 43,
    category: "Saladas & Cia",
  },
  {
    id: 2,
    name: "Salada de Grãos",
    desc: "Mix de folhas frescas, grão de bico...",
    price: 43,
    category: "Saladas & Cia",
  },
  {
    id: 3,
    name: "Omelete com Salada",
    desc: "Omelete com queijo, presunto...",
    price: 33,
    category: "Saladas & Cia",
  },
  {
    id: 4,
    name: "Saint Peter Empanado",
    desc: "Com purê de abóbora...",
    price: 54,
    category: "Pratos",
  },
  {
    id: 5,
    name: "Filé de Frango Grelhado",
    desc: "Com creme de milho, arroz e salada...",
    price: 43,
    category: "Pratos",
  },
  {
    id: 6,
    name: "Saint Peter Empanado",
    desc: "Com purê de abóbora...",
    price: 54,
    category: "Pratos",
  },
  {
    id: 7,
    name: "Filé de Frango Grelhado",
    desc: "Com creme de milho, arroz e salada...",
    price: 43,
    category: "Pratos",
  },
  {
    id: 8,
    name: "Saint Peter Empanado",
    desc: "Com purê de abóbora...",
    price: 54,
    category: "Pratos",
  },
  {
    id: 9,
    name: "Filé de Frango Grelhado",
    desc: "Com creme de milho, arroz e salada...",
    price: 43,
    category: "Pratos",
  },
  {
    id: 10,
    name: "Saint Peter Empanado",
    desc: "Com purê de abóbora...",
    price: 54,
    category: "Pratos",
  },
  {
    id: 11,
    name: "Filé de Frango Grelhado",
    desc: "Com creme de milho, arroz e salada...",
    price: 43,
    category: "Pratos",
  },
  {
    id: 12,
    name: "Saint Peter Empanado",
    desc: "Com purê de abóbora...",
    price: 54,
    category: "Pratos",
  },
  {
    id: 13,
    name: "Filé de Frango Grelhado",
    desc: "Com creme de milho, arroz e salada...",
    price: 43,
    category: "Pratos",
  },
  {
    id: 14,
    name: "Saint Peter Empanado",
    desc: "Com purê de abóbora...",
    price: 54,
    category: "Pratos",
  },
  {
    id: 15,
    name: "Filé de Frango Grelhado",
    desc: "Com creme de milho, arroz e salada...",
    price: 43,
    category: "Pratos",
  },
  {
    id: 16,
    name: "Saint Peter Empanado",
    desc: "Com purê de abóbora...",
    price: 54,
    category: "Pratos",
  },
  {
    id: 17,
    name: "Filé de Frango Grelhado",
    desc: "Com creme de milho, arroz e salada...",
    price: 43,
    category: "Pratos",
  },
  {
    id: 18,
    name: "Saint Peter Empanado",
    desc: "Com purê de abóbora...",
    price: 54,
    category: "Pratos",
  },
  {
    id: 19,
    name: "Filé de Frango Grelhado",
    desc: "Com creme de milho, arroz e salada...",
    price: 43,
    category: "Pratos",
  },
  {
    id: 20,
    name: "Saint Peter Empanado",
    desc: "Com purê de abóbora...",
    price: 54,
    category: "Pratos",
  },
  {
    id: 21,
    name: "Filé de Frango Grelhado",
    desc: "Com creme de milho, arroz e salada...",
    price: 43,
    category: "Pratos",
  },
  {
    id: 22,
    name: "Saint Peter Empanado",
    desc: "Com purê de abóbora...",
    price: 54,
    category: "Pratos",
  },
  {
    id: 23,
    name: "Filé de Frango Grelhado",
    desc: "Com creme de milho, arroz e salada...",
    price: 43,
    category: "Pratos",
  },
  {
    id: 24,
    name: "Saint Peter Empanado",
    desc: "Com purê de abóbora...",
    price: 54,
    category: "Pratos",
  },
  {
    id: 25,
    name: "Filé de Frango Grelhado",
    desc: "Com creme de milho, arroz e salada...",
    price: 43,
    category: "Pratos",
  },
];
